server:
  port: 7882
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.6.238:3306/micro-graphy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: $xdkj@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 100
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: select 1
  redis:
    redisson:
      config: classpath:redisson/redisson-test.yml
    host: 127.0.0.1
    port: 6379
    password: hewenping
    database: 6
    jedis:
      pool:
        #最大空闲数，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
        max-idle: 300
        min-idle: 20
        #连接池的最大数据库连接数。设为0表示无限制
        max-active: 600
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 2000
# 日志配置
logging:
  config: classpath:logback/logback-test.xml
#项目自定义属性配置
pro:
  #文件保存路径
  file-folder: D:/project/xdkj/Source/trunk/server/micro-graphy/graphy-upload-file