server:
  servlet:
    #二级目录配置 例:/lsk
    context-path: /graphy
spring:
  # 环境 dev|pro|test
  profiles:
    active: pro
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #网页静态资源文件夹
  resources:
    static-locations: classpath:/thymeleaf/static  #前缀
    #thymeleaf配置
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/thymeleaf/html  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
    servlet:
      content-type: text/html
# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/com/graphy/**/xml/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: input
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true
#区块链存储接口地址
storage-host: http://pacs.micro-recruit.com:6080/addDepositCert
#区块链提取接口地址
extract-host: http://pacs.micro-recruit.com:6080/queryDepositCert